name: lopa-frontend-ci-pipeline
trigger:
- none
stages:
- stage:
  jobs:
  - job:
    pool: 
      lopa-agent
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'lopa-service'
        repository: 'lopanath12345/itc-project'
        command: 'buildAndPush'
        dockerfile: 'Dockerfile'
        tags: 'lopa-frontend-image-new21'